# Generated by Django 5.2.5 on 2025-09-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_user_to_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
