# Generated by Django 5.2.5 on 2025-08-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_customer_profile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
    ]
